import { describe, expect, test } from "vitest";
import {
    calculateTax,
    isValidIncome,
} from "../src/taxCalculator.js";

describe("isValidIncome", () => {
    test("rejects null", () => {
        expect(isValidIncome(null)).toBe(false);
    });

    test("rejects undefined", () => {
        expect(isValidIncome(undefined)).toBe(false);
    });

    test("rejects a negative income", () => {
        expect(isValidIncome(-100)).toBe(false);
    });

    test("rejects zero", () => {
        expect(isValidIncome(0)).toBe(false);
    });

    test("accepts 1,999.99", () => {
        expect(isValidIncome(1999.99)).toBe(true);
    });

    test("accepts 2,000.00", () => {
        expect(isValidIncome(2000)).toBe(true);
    });

    test("accepts 2,000.01", () => {
        expect(isValidIncome(2000.01)).toBe(true);
    });

    test("accepts 3,000.00", () => {
        expect(isValidIncome(3000)).toBe(true);
    });

    test("accepts 3,000.01", () => {
        expect(isValidIncome(3000.01)).toBe(true);
    });

    test("accepts 5,000.00", () => {
        expect(isValidIncome(5000)).toBe(true);
    });

    test("accepts 5,000.01", () => {
        expect(isValidIncome(5000.01)).toBe(true);
    });

    test("accepts a large finite income", () => {
        expect(isValidIncome(1_000_000_000)).toBe(true);
    });

    test("accepts a decimal with more than two decimal places", () => {
        expect(isValidIncome(2500.1234)).toBe(true);
    });

    test("rejects NaN", () => {
        expect(isValidIncome(Number.NaN)).toBe(false);
    });

    test("rejects positive infinity", () => {
        expect(isValidIncome(Infinity)).toBe(false);
    });

    test("rejects negative infinity", () => {
        expect(isValidIncome(-Infinity)).toBe(false);
    });
});

describe("calculateTax", () => {
    test("returns the gross income", () => {
        const result = calculateTax(6000);

        expect(result.gross_income).toBe(6000);
    });

    test("returns no tax below the exempt limit", () => {
        const result = calculateTax(1999.99);

        expect(result.total_tax).toBeCloseTo(0);
    });

    test("returns no tax exactly at the exempt limit", () => {
        const result = calculateTax(2000);

        expect(result.total_tax).toBeCloseTo(0);
    });

    test("taxes only one cent above the exempt limit", () => {
        const result = calculateTax(2000.01);

        expect(result.total_tax).toBeCloseTo(0.001);
    });

    test("calculates a partially filled 10% bracket", () => {
        const result = calculateTax(2500);

        expect(result.total_tax).toBeCloseTo(50);
    });

    test("calculates tax exactly at 3,000", () => {
        const result = calculateTax(3000);

        expect(result.total_tax).toBeCloseTo(100);
    });

    test("taxes only one cent in the 20% bracket", () => {
        const result = calculateTax(3000.01);

        expect(result.total_tax).toBeCloseTo(100.002);
    });

    test("calculates a partially filled 20% bracket", () => {
        const result = calculateTax(4000);

        expect(result.total_tax).toBeCloseTo(300);
    });

    test("calculates tax exactly at 5,000", () => {
        const result = calculateTax(5000);

        expect(result.total_tax).toBeCloseTo(500);
    });

    test("taxes only one cent in the 30% bracket", () => {
        const result = calculateTax(5000.01);

        expect(result.total_tax).toBeCloseTo(500.003);
    });

    test("calculates tax across every bracket", () => {
        const result = calculateTax(6000);

        expect(result.total_tax).toBeCloseTo(800);
    });

    test("calculates net income", () => {
        const result = calculateTax(6000);

        expect(result.net_income).toBeCloseTo(5200);
    });

    test("calculates the effective tax rate", () => {
        const result = calculateTax(6000);

        expect(result.effective_tax_rate).toBeCloseTo(800 / 6000);
    });

    test("returns the tax generated by each bracket", () => {
        const result = calculateTax(6000);

        expect(result.bracket_taxes_list).toHaveLength(4);
        expect(result.bracket_taxes_list[0]).toBeCloseTo(0);
        expect(result.bracket_taxes_list[1]).toBeCloseTo(100);
        expect(result.bracket_taxes_list[2]).toBeCloseTo(400);
        expect(result.bracket_taxes_list[3]).toBeCloseTo(300);
    });

    test("returns zero for brackets not reached by the income", () => {
        const result = calculateTax(2500);

        expect(result.bracket_taxes_list).toHaveLength(4);
        expect(result.bracket_taxes_list[0]).toBeCloseTo(0);
        expect(result.bracket_taxes_list[1]).toBeCloseTo(50);
        expect(result.bracket_taxes_list[2]).toBeCloseTo(0);
        expect(result.bracket_taxes_list[3]).toBeCloseTo(0);
    });

    test("calculates a value inside the highest bracket", () => {
        const result = calculateTax(10_000);

        expect(result.total_tax).toBeCloseTo(2000);
    });

    test("calculates tax for a large finite income", () => {
        const result = calculateTax(1_000_000_000);

        expect(result.total_tax).toBeCloseTo(299_999_000);
    });

    test("preserves precision before final formatting", () => {
        const result = calculateTax(2500.1234);

        expect(result.total_tax).toBeCloseTo(50.01234);
    });

    test("does not tax the entire income at the 10% rate after crossing 2,000", () => {
        const result = calculateTax(2001);

        expect(result.total_tax).toBeCloseTo(0.1);
    });

    test("does not tax the entire income at the 20% rate after crossing 3,000", () => {
        const result = calculateTax(3001);

        expect(result.total_tax).toBeCloseTo(100.2);
    });

    test("does not tax the entire income at the 30% rate after crossing 5,000", () => {
        const result = calculateTax(5001);

        expect(result.total_tax).toBeCloseTo(500.3);
    });

    test("total tax never decreases when income increases", () => {
        const incomes = [
            1000,
            1999.99,
            2000,
            2000.01,
            2500,
            3000,
            3000.01,
            4000,
            5000,
            5000.01,
            6000,
        ];

        for (let i = 1; i < incomes.length; i++) {
            const previousIncome = incomes[i - 1]!;
            const currentIncome = incomes[i]!;

            const previousResult = calculateTax(previousIncome);
            const currentResult = calculateTax(currentIncome);

            expect(currentResult.total_tax).toBeGreaterThanOrEqual(
                previousResult.total_tax
            );
        }
    });

    test("gross income equals tax plus net income", () => {
        const result = calculateTax(6000);

        expect(result.total_tax + result.net_income).toBeCloseTo(
            result.gross_income
        );
    });
});